name: Test build debian package

on:
  push:
    # branches:
    #   - main
    # tags:
    #   - "*"
  pull_request:
    types:
      - opened
      - edited

env:
  DEBIAN_FRONTEND: noninteractive
  DEBCONF_NONINTERACTIVE_SEEN: true
  TERM: dumb

jobs:
  build_deb:
    name: Test build debian package
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install ubuntu-dev-tools

      - name: Get package source
        run: |
          set -eu

          pull-lp-source --download-only hello
          dpkg-source -x hello*.dsc hello-src
          rm -rf hello_*
          mv -v hello-src/* .

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: .source

      - name: See what's around
        run: find

      - name: Build package
        uses: ./.source/gh-actions/common/build-debian
