name: Test build debian package

on:
  push:
    branches:
    #   - main
    # tags:
    #   - "*"
  pull_request:

env:
  DEBIAN_FRONTEND: noninteractive
  DEBCONF_NONINTERACTIVE_SEEN: true
  TERM: dumb

jobs:
  build_native_deb:
    name: Test build native debian package
    runs-on: ubuntu-latest
    outputs:
      pkg-name: ${{ env.PKG_NAME }}
      pkg-version: ${{ env.PKG_VERSION }}

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install ubuntu-dev-tools

      - name: Get and prepare package source
        run: |
          set -eu

          echo "::group::Get source"
          pull-lp-source --download-only hello
          dpkg-source -x hello*.dsc hello-src
          rm -rf hello_*
          mv -v hello-src/* .
          echo "::endgroup::"

          echo "::group::Mark package as a native package"
          echo "3.0 (native)" > debian/source/format
          dch -v$(dpkg-parsechangelog -S Version | cut -f1 -d-).1 \
            "Mark as native package"
          echo "::endgroup::"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: .source

      - name: Build package
        uses: ./.source/gh-actions/common/build-debian
        with:
          docker-image: ubuntu:devel

  build_source_deb:
    name: Test build quilt debian package
    runs-on: ubuntu-latest
    outputs:
      run-id: ${{ github.run_id }}
      source-pkg: ${{ steps.build-debian-source-package-upload-step.outputs.artifact-url }}
      binaries: ${{ steps.build-debian-binary-packages-upload-step.outputs.artifact-url }}
      pkg-name: ${{ env.PKG_NAME }}
      pkg-version: ${{ env.PKG_VERSION }}

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install ubuntu-dev-tools

      - name: Get package source
        run: |
          set -eu

          pull-lp-source --download-only hello
          dpkg-source -x hello*.dsc hello-src

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: .source

      - name: Build package
        uses: ./.source/gh-actions/common/build-debian
        with:
          source-dir: ./hello-src
          docker-image: ubuntu:devel
          extra-source-build-deps: ''

      # - name: Archiving built debs
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: debian-packages
      #     path: ${{ env.BUILD_OUTPUT_DIR }}
      #     if-no-files-found: error

      # - name: Archiving built sources
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: debian-sources
      #     path: ${{ env.SOURCE_OUTPUT_DIR }}
      #     if-no-files-found: error

  run-lintian:
    name: Run lintian
    needs: build_source_deb
    runs-on: ubuntu-latest

    container:
      image: ubuntu:devel

    steps:
    - name: Prepare container
      run: |
        set -eu

        echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90aptyes
        apt update

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ needs.build_source_deb.outputs.run-id }}

    - name: Install dependencies
      run: |
        apt install lintian

    - name: Create test user
      run: |
        apt install adduser
        adduser --disabled-password --gecos "" tester
        chown tester:tester . -R

    - name: Run lintian on source package
      run: |
        runuser -u tester -- lintian --pedantic --fail-on error \
          ./*-debian-source/${{ needs.build_source_deb.outputs.pkg-name }}_${{ needs.build_source_deb.outputs.pkg-version }}_source.changes

    - name: Run lintian on binary packages
      run: |
        runuser -u tester -- lintian --pedantic --fail-on error \
          ./*-debian-packages/*_${{ needs.build_source_deb.outputs.pkg-version }}_*.deb

  run-autopkgtests:
    name: Run autopkgtests
    needs: build_source_deb
    runs-on: ubuntu-latest

    container:
      image: ubuntu:devel

    steps:
    - name: Prepare container
      run: |
        set -eu

        echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90aptyes
        apt update

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ needs.build_source_deb.outputs.run-id }}

    - name: Install dependencies
      run: |
        apt install autopkgtest

    - name: Run autopkgtests
      run: |
        mv -v ./*-debian-source/* .
        mv -v ./*-debian-packages/* .
        autopkgtest --apt-pocket proposed --apt-upgrade --no-built-binaries \
          *_${{ needs.build_source_deb.outputs.pkg-version }}*.deb \
          ${{ needs.build_source_deb.outputs.pkg-name }}_${{ needs.build_source_deb.outputs.pkg-version }}_source.changes -- null
